# Generated by Django 4.1 on 2022-09-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('post_type', models.CharField(db_column='post_type', max_length=255, verbose_name='post_type')),
                ('title', models.CharField(db_column='title', default='', max_length=255, verbose_name='title')),
                ('start_operating_period', models.DateField(db_column='start_operating_period', default='', verbose_name='start_operating_period')),
                ('finish_operating_period', models.DateField(db_column='finish_operating_period', default='', verbose_name='finish_operating_period')),
                ('start_apply_period', models.DateField(db_column='start_apply_period', default='', verbose_name='start_apply_period')),
                ('finish_apply_period', models.DateField(db_column='finish_apply_period', default='', verbose_name='finish_apply_period')),
                ('content', models.TextField(db_column='content', default='', verbose_name='content')),
                ('thumbnail', models.ImageField(blank=True, db_column='thumbnail', null=True, upload_to='uploads', verbose_name='thumbnail')),
                ('link', models.TextField(db_column='link', default='', verbose_name='link')),
                ('disabled', models.BooleanField(db_column='post_disabled', default=False, verbose_name='post_disabled')),
            ],
        ),
    ]
